alter table public.product_settings
  add column if not exists topbar_text text,
  add column if not exists topbar_color text,
  add column if not exists badge_text text,
  add column if not exists hero_title text,
  add column if not exists hero_highlight text,
  add column if not exists subhero_text text,
  add column if not exists sales_count integer,
  add column if not exists cod_text text,
  add column if not exists countdown_active boolean default true,
  add column if not exists countdown_hours integer default 2,
  add column if not exists countdown_minutes integer default 47,
  add column if not exists upsell_active boolean default true,
  add column if not exists upsell_title text,
  add column if not exists upsell_text text,
  add column if not exists upsell_value integer,
  add column if not exists whatsapp text,
  add column if not exists reviews_active boolean default true,
  add column if not exists review1_name text,
  add column if not exists review1_city text,
  add column if not exists review1_text text,
  add column if not exists review2_name text,
  add column if not exists review2_city text,
  add column if not exists review2_text text,
  add column if not exists review3_name text,
  add column if not exists review3_city text,
  add column if not exists review3_text text;
